CasrAsanBacktraceObserver to dedupe crashes using libCASR and ASAN reports.
AFLplusplus/LibAFL pull request #1184
Opened 2023-03-27 11:30 UTC by anfedotoff

2023-03-27 12:04 UTC, SweetVishnya requested changes

2023-03-27 12:04 UTC, SweetVishnya commented on libafl/src/observers/casr.rs
> +        asan_output.read_to_string(&mut buf)?;
utf8 lossy?

2023-03-27 14:28 UTC, SweetVishnya approved these changes

2023-03-27 18:24 UTC, domenukk commented on fuzzers/backtrace_baby_fuzzers/command_executor/src/main.rs
> +cfg_if::cfg_if! {
You won't need a crate here, you can do
```rust
#[cfg(feature = "casr")]
use libafl::observers::CasrAsanBacktraceObserver;
#[cfg(not(feature = "casr"))]
use libafl::observers::AsanBacktraceObserver;
```
or maybe even just always enable AsanBacktraceObserver, even for the casr feature - why not?

2023-03-30 15:38 UTC, anfedotoff commented
@domenukk, suddenly I realized this: CasrAsanObserver and AsanBacktraceObserver are the same expect for this function:
https://github.com/AFLplusplus/LibAFL/blob/a01863696e186c0d57acdc6789e16d59ce96c01f/libafl/src/observers/stacktrace.rs#L226
Maybe I use `feature = "casr"` / `not(feature = "casr")` to switch between this functions? This will reduce code significantly.
The same thing I could do for:
https://github.com/AFLplusplus/LibAFL/blob/a01863696e186c0d57acdc6789e16d59ce96c01f/libafl/src/observers/stacktrace.rs#L28
So all stacktrace observes could switch between hashing algorithms. All examples should work without any code modification! What do you think?

2023-04-01 14:01 UTC, SweetVishnya requested changes

2023-04-01 14:01 UTC, SweetVishnya commented on libafl/src/observers/stacktrace.rs
> +                init_ignored_frames!("rust", "cpp", "go");
same here, we should init this only once

2023-04-01 14:16 UTC, anfedotoff commented on libafl/src/observers/stacktrace.rs
> +    for frame in &b.frames()[1..] {
I suppose, no. According to this: https://docs.rs/backtrace/latest/backtrace/struct.Backtrace.html#method.frames

2023-04-03 08:44 UTC, anfedotoff commented
I think now it's ready! @domenukk, please, could you have a look?

2023-04-03 10:06 UTC, SweetVishnya requested changes

2023-04-03 10:06 UTC, SweetVishnya commented on libafl/src/observers/stacktrace.rs
> +        init_ignored_frames!("rust", "cpp");
why not adding go here?

2023-04-04 10:16 UTC, SweetVishnya approved these changes

2023-04-04 15:07 UTC, anfedotoff commented
Btw, I tested AsanBacktraceObserver with CASR on some real world example https://github.com/tfussell/xlnt. For this purpose I modified `forkserver_simple` and cherry-picked this fix #1189. It seems to work! If we need this example I could prepare.

2023-04-04 17:03 UTC, tokatoka commented
looks good thank you!

2023-04-04 17:03 UTC, merged