Feature required: allow the FridaInProcessExecutor to attach Stalker on specific thread
AFLplusplus/LibAFL pull request #1256
Opened 2023-05-06 10:42 UTC by r4ve1

In certain cases, such as when fuzzing p2p protocols, the fuzzer may run on a different thread than the target function (i.e., the execution is asynchronous). However, the current implementation of `FridaInProcessExecutor` in LibAFL only allows coverage to be collected on the thread where the fuzzer runs, by attaching a stalker using `Stalker::follow_me`.

To address this limitation, I have submitted a pull request that upgrades the `frida-gum` dependency to the latest version, which exposes the `Stalker::follow` API. I have also made some changes to the code that enable users to specify the `thread_id` where coverage should be collected. However, since this update involves breaking the ABI, it is currently only a proof of concept.

2023-05-07 12:33 UTC, r4ve1 commented
@domenukk @andreafioraldi any suggestions or supports? Thanks :)

2023-05-08 12:15 UTC, domenukk commented
@WorksButNotTested @s1341 FYI

2023-05-08 12:51 UTC, WorksButNotTested commented
Sounds good. Like you say the capstone issue needs sorting before you can bump the version. 

Would it be more flexible perhaps to allow multiple threads or all threads to be stalked rather than just one?

Also worth bearing in mind that multiple threads don’t play well with the fork server. Otherwise I can’t see a problem.

2023-05-09 11:26 UTC, domenukk commented
A related issue is #68 - it also suggested to hook process/thread creation and continue stalking these

2023-08-02 11:50 UTC, domenukk commented
This got unblocked thanks to https://github.com/frida/frida-rust/pull/99 - I guess we can merge this once we update frida

2023-08-02 13:10 UTC, s1341 requested changes
LGTM.

Please update the frida-based fuzzers to use the new API.

2023-08-09 18:45 UTC, domenukk commented
We can tackle this after #1408

2023-08-17 17:47 UTC, merged

2023-08-18 08:52 UTC, domenukk commented
Instead of fixing all fuzzers, #1427 introduces the `on_thread` constructor that stalkes a given thread