qemu snapshot little update proposal.
AFLplusplus/LibAFL pull request #1431
Opened 2023-08-20 10:55 UTC by devnexen

2023-08-21 11:54 UTC, devnexen commented on libafl_qemu/src/snapshot.rs
> +                if let Ok(prot) = MmapPerms::try_from(a3 as i32) {
Looking at this now, I m not sure this is correct here. like mixing oranges and apples kind of thing.

2023-08-22 08:08 UTC, andreafioraldi requested changes

2023-08-22 08:08 UTC, andreafioraldi commented on libafl_qemu/src/snapshot.rs
> +                h.remove_mapped(a0 as GuestAddr, a1 as usize);
Why remove and add are swapped here?

2023-08-22 11:26 UTC, devnexen commented on libafl_qemu/src/snapshot.rs
> +                h.remove_mapped(a0 as GuestAddr, a1 as usize);
I just forgot to put it back.

2023-08-23 08:13 UTC, andreafioraldi approved these changes

2023-08-23 08:13 UTC, merged