No uses from mutational.rs and power.rs
AFLplusplus/LibAFL pull request #2470
Opened 2024-08-02 12:35 UTC by tokatoka

Don't rebase next time lol

2024-08-02 12:36 UTC, tokatoka commented on libafl/src/stages/pruning.rs
> -//! Corpus pruning stage
this one currently doesn't work. i have a working one in my repo. i'll commit after the experiment on fuzzbench

2024-08-02 12:51 UTC, addisoncrump commented
rebase good

2024-08-03 21:54 UTC, tokatoka commented
can you merge this if it's ok?

2024-08-04 22:22 UTC, addisoncrump requested changes
Just a couple of notes here. Mainly, we shouldn't introduce *any* constraints unless they are necessary for the specific definition.

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/corpus/mod.rs
> +    type Input: Debug;
Shouldn't be here. It makes only a couple of the constraints later simpler, but IMO makes things less clean.

Is there a specific reason you added this?

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/executors/mod.rs
> +#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, Eq)]
This won't work, because ExitKind is not Copy-able.

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/observers/map/mod.rs
> +    type Entry: PartialEq + Copy + Debug + Serialize + DeserializeOwned;
Again, this isn't necessary for the trait definition. Why was this added?

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/schedulers/mod.rs
> +// pub mod accounting;
Intentional?

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/schedulers/testcase_score.rs
>  }
I'm not sure I like this. That said, `TestcaseScore` is only used with schedulers, so this is probably fine.

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/stages/power.rs
>  }
*chef's kiss*

2024-08-04 22:22 UTC, addisoncrump commented on libafl/src/stages/mutational.rs
> +    type M;
Associated type names should have meaningful names, e.g. `Mutators`.

2024-08-05 11:46 UTC, addisoncrump commented
> all the structs in LibAFL should implement Debug

Yes, but it isn't required for the trait definition, so we shouldn't include it as this may require that impls have more constraints unnecessarily (`Debug` isn't required to return a `&T`).

Similarly, yes, while the observers should be serializable, it's not something that is necessary for any of the trait items, so it shouldn't be included.

2024-08-05 13:10 UTC, tokatoka commented
fixed all

2024-08-05 13:48 UTC, merged