No uses from EventManager
AFLplusplus/LibAFL pull request #2482
Opened 2024-08-09 15:46 UTC by tokatoka

After several attempts, I finally got how i can do this.

2024-08-12 17:34 UTC, tokatoka commented
@addisoncrump 
This is done

2024-08-12 17:46 UTC, tokatoka commented
maybe i should make all EMH associate type?

2024-08-12 18:38 UTC, tokatoka commented
no nevermind this was not a trait

2024-08-13 12:20 UTC, addisoncrump requested changes

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>      DI: Input,
Do we need the generics here at all? This is a struct definition.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>          DI: Input,
Likewise, don't need these.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>          DI: Input,
Or these?

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>          DI: Input,
Again

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>      DI: Input,
Just need `IC: Debug, ICB: Debug`.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/mod.rs
>      DI: Input,
Please remove `phantom` from the debugged items.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/restarting.rs
> +        >,
Hm, this is a ton of generics. Are they all truly necessary?

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/llmp/restarting.rs
> +    for<'de> E::Observers: DeserializeOwned,
`for<'de> ` can be removed.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/simple.rs
> +                "Received illegal message that message should not have arrived"
We lose a bit of debugging here. It's probably okay to specify `<S::Corpus as Corpus>::Input: Debug`.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/simple.rs
> +            .field("monitor", &self.inner)
This is incorrectly named.

2024-08-13 12:20 UTC, addisoncrump commented on libafl/src/events/tcp.rs
Eventually, we should figure out how to merge this with llmp (maybe some "channel" abstraction?). The code is mostly duplicated and I can see other event managers in the future that specify other means by which to communicate.

2024-08-13 12:24 UTC, tokatoka commented on libafl/src/events/llmp/restarting.rs
> +    for<'de> E::Observers: DeserializeOwned,
ok

2024-08-13 12:32 UTC, tokatoka commented on libafl/src/events/tcp.rs
this one is supposed to be superceded by multimachine.
plus it can't even connect to other host with current implementation

2024-08-13 12:37 UTC, addisoncrump commented on libafl/src/events/tcp.rs
So, should we simply remove it?

2024-08-13 12:38 UTC, tokatoka commented on libafl/src/events/tcp.rs
domenukk doesn't want to remove it.

2024-08-13 12:40 UTC, addisoncrump commented on libafl/src/events/tcp.rs
Okay, we'll leave it for now. @domenukk, is there a particular reason you want to keep this guy around? Feels like debt.

2024-08-13 13:22 UTC, tokatoka commented
fixed all @addisoncrump

2024-08-13 13:30 UTC, addisoncrump approved these changes

2024-08-13 13:32 UTC, merged